In [1]:
import numpy as np


a1 = np.array([10, 20, 30, 40, 50])
print("1D Array:", a1)
print("Indexing a1[2]:", a1[2])
print("Slicing a1[1:4]:", a1[1:4])


a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
print("\n2D Array:\n", a2)
print("Element a2[1][2]:", a2[1][2])
print("First row:", a2[0, :])


a3 = np.array([[[1, 2], [3, 4]],
               [[5, 6], [7, 8]]])
print("\n3D Array:\n", a3)
print("Element a3[1][0][1]:", a3[1][0][1])


1D Array: [10 20 30 40 50]
Indexing a1[2]: 30
Slicing a1[1:4]: [20 30 40]

2D Array:
 [[1 2 3]
 [4 5 6]]
Element a2[1][2]: 6
First row: [1 2 3]

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Element a3[1][0][1]: 6


In [2]:
import numpy as np

a = np.array([[10, 20, 30],
              [40, 50, 60]])

print("Array:\n", a)


print("Addition:", a + 5)
print("Subtraction:", a - 5)
print("Multiplication:", a * 2)
print("Division:", a / 2)


print("Sum:", np.sum(a))
print("Mean:", np.mean(a))
print("Max:", np.max(a))
print("Min:", np.min(a))
print("Standard Deviation:", np.std(a))


Array:
 [[10 20 30]
 [40 50 60]]
Addition: [[15 25 35]
 [45 55 65]]
Subtraction: [[ 5 15 25]
 [35 45 55]]
Multiplication: [[ 20  40  60]
 [ 80 100 120]]
Division: [[ 5. 10. 15.]
 [20. 25. 30.]]
Sum: 210
Mean: 35.0
Max: 60
Min: 10
Standard Deviation: 17.07825127659933


In [3]:
import numpy as np

a = np.array([[3, 1, 2],
              [6, 5, 4]])

print("Original Array:\n", a)


print("Transpose:\n", a.T)


print("Sorted Array:\n", np.sort(a))


b = a.reshape(3, 2)
print("Reshaped Array (3x2):\n", b)


Original Array:
 [[3 1 2]
 [6 5 4]]
Transpose:
 [[3 6]
 [1 5]
 [2 4]]
Sorted Array:
 [[1 2 3]
 [4 5 6]]
Reshaped Array (3x2):
 [[3 1]
 [2 6]
 [5 4]]


In [4]:
import numpy as np

print("Zeros Array:\n", np.zeros((2, 3)))


print("Ones Array:\n", np.ones((3, 2)))


print("Identity Matrix:\n", np.eye(3))


print("Arange Array:", np.arange(1, 10, 2))


print("Linspace Array:", np.linspace(1, 10, 5))


print("Random Array:\n", np.random.rand(2, 2))


Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Arange Array: [1 3 5 7 9]
Linspace Array: [ 1.    3.25  5.5   7.75 10.  ]
Random Array:
 [[0.56981006 0.12132523]
 [0.3569775  0.3830683 ]]
